package com.sample.app.broker;


public class Message {

    private final int partition;
    private final long messageOffset;

    private final String deviceId;
    private final short deliveryId;
    private final String body;

    public Message(int partition, long messageOffset, String deviceId, short deliveryId, String body) {
        if (deviceId == null) {
            throw new IllegalArgumentException("Argument 'deviceId' must not be null");
        }

        if (body == null) {
            throw new IllegalArgumentException("Argument 'body' must not be null");
        }

        this.partition = partition;
        this.messageOffset = messageOffset;
        this.deviceId = deviceId;
        this.deliveryId = deliveryId;
        this.body = body;
    }

    /**
     * The number of the partition from which the message was read. Messages of a particular device are ALWAYS
     * in the same partition.
     */
    public int getPartition() {
        return partition;
    }

    /**
     * The technical message offset as generated by the queuing system. It increases monotonically within a partition
     * for each new message.
     */
    public long getOffset() {
        return messageOffset;
    }

    /**
     * A unique identifier of a device.
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * An ID which starts at 1 and increases monotonically for every message of the same device.
     *
     * It will wrap around after {@link Short#MAX_VALUE}
     */
    public short getDeliveryId() { return deliveryId; }

    /**
     * Content of the message, as written to the topic.
     */
    public String getBody() {
        return body;
    }
}
